### ISSUE TITLE
Requesting code for this paper

### ISSUE THREAD

**Issue by sai1992c** [chenfengxu714/image2point#1]
Hi,

I went through this paper and really fascinated by your work.  I'm really eager to reproduce the results from this paper, however the code is still not available. Will you be checking in the code soon? Will be of great help to me.

Thanks in advance. :)

**Comment by chenfengxu714** [comment]
Hi, sincerely thanks for your appreciation of our work. In fact, we have finished the code checking and reviewing. Yet after discussing with my coauthors, we decide to release the code as soon as possible when this work is formally published. Sorry for making you wait.

**Comment by lilanxiao** [comment]
@sai1992c hi, I'm working on reproducing this paper. Here is my repo: https://github.com/lilanxiao/image2point
My code is still under construction and cannot reproduce the reported results yet. But I hope it can help before the official code is available. Any suggestions and contributions are welcome.

**Comment by chenfengxu714** [comment]
@lilanxiao , hi, nice reproduction version! After read your known issue in your repo, we think you almost reach our version. Something may help you to get our results, 78 acc comes from the non-linear input and output layer, you may refer our supplementary. You may also train the model longer, I think the performance can be much better. 

Another thing I want to mention here is that your random initialization experiments, in fact, we also find this interesting thing! We have already prepared a totally new version of this paper, in which we will present this comparison as well as something others I believe very interesting!

**Comment by lilanxiao** [comment]
@chenfengxu714 hi, thank you very much for the suggestions! Hope I could fix my code soon. BTW, I'm looking forward to the new version of the paper. Would it be uploaded to Arxiv or directly published at a conference?

**Comment by sai1992c** [comment]
> Hi, sincerely thanks for your appreciation of our work. In fact, we have finished the code checking and reviewing. Yet after discussing with my coauthors, we decide to release the code as soon as possible when this work is formally published. Sorry for making you wait.

Really sorry for the late reply. I can't thank you much for your kind response. Awaiting your implementation to learn more :)

**Comment by sai1992c** [comment]
> @sai1992c hi, I'm working on reproducing this paper. Here is my repo: https://github.com/lilanxiao/image2point
> My code is still under construction and cannot reproduce the reported results yet. But I hope it can help before the official code is available. Any suggestions and contributions are welcome.

Great effort @lilanxiao. Definite will look at it ..!

**Comment by chenfengxu714** [comment]
Released code.
