### ISSUE TITLE
no requirement.txt

### ISSUE THREAD

**Issue by HalvesChen** [chenfengxu714/image2point#2]
Hi, The requirement.txt is not available in github, when will it be available? :)

**Comment by bronyayang** [comment]
@chendaozai Hi, 
Thank you for your reminder! requirements.txt is uploaded! However, my environment was created several months ago using this file. I know there may be some minor issues using this requirement.txt now. If anything comes up, please re-open this issue and fix it together.

**Comment by HalvesChen** [comment]
> @chendaozai Hi, Thank you for your reminder! requirements.txt is uploaded! However, my environment was created several months ago using this file. I know there may be some minor issues using this requirement.txt now. If anything comes up, please re-open this issue and fix it together.

Thanks for your reply, I would also like to ask how much video memory is needed when you fine tune on  semantic segmentation task?

**Comment by bronyayang** [comment]
> Thanks for your reply, I would also like to ask how much video memory is needed when you fine tune on semantic segmentation task?

If you mean gpu memory for segmentation task, it is below 24G per GPU for any model architecture.

**Comment by chendaozai** [comment]
> If you mean gpu memory for segmentation task, it is below 24G per GPU for any model architecture.
Thanks :)
