### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by HalvesChen** [chenfengxu714/image2point#3]
when I run the commad 'torchpack dist-run -np 2 python train.py configs/s3dis/from_scratch.yaml --run-dir ./s3dis_out' , I got a error as follows. Could you please tell me how can I resolve this problem? Thanks very much!
![image](https://user-images.githubusercontent.com/55949813/184534269-02f6ba75-dc3e-4650-b520-f8e5fdd8c093.png)

**Comment by bronyayang** [comment]
According to this post (https://stackoverflow.com/questions/33780992/mpirun-unrecognized-argument-mca), you can try to install open mpi.
See if `sudo apt install mpich` then install py4my works for you.
